/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    HeroJumbotron: typeof import('./src/components/HeroJumbotron.vue')['default']
    ImageComponent: typeof import('./src/components/ImageComponent.vue')['default']
    OrientationWarning: typeof import('./src/components/OrientationWarning.vue')['default']
    PageLoader: typeof import('./src/components/PageLoader.vue')['default']
    PhotoGallery: typeof import('./src/components/PhotoGallery.vue')['default']
    ProjectCards: typeof import('./src/components/ProjectCards.vue')['default']
    ProjectsJumbotron: typeof import('./src/components/ProjectsJumbotron.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionDivider: typeof import('./src/components/SectionDivider.vue')['default']
    StorySection: typeof import('./src/components/StorySection.vue')['default']
    TechSkillsCarousel: typeof import('./src/components/TechSkillsCarousel.vue')['default']
  }
}
