/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    HeroJumbotron: typeof import('./src/components/HeroJumbotron.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplidejsCarousel: typeof import('./src/components/SplidejsCarousel.vue')['default']
    TechSkillsCarousel: typeof import('./src/components/TechSkillsCarousel.vue')['default']
  }
}
